### ISSUE TITLE
AttributeError: 'os.stat_result' object has no attribute 'st_birthtime'

### ISSUE THREAD

**Issue by Jomme5** [erbsland-dev/fast-file-encryption#1]
Error in encryptor.py --> `source.stat().st_birthtime` on line 367 of encryptor.py

There is no such thing as `.st_birthtime`. Please change it to `.ST_CTIME` accordingly the [docs](https://docs.python.org/3/library/stat.html)

Thanks

**Comment by Exordio** [comment]
++

**Comment by erbsland-dev** [comment]
Sorry, about the lack of reaction about this issue and thank you for submitting this fix.

The way how the repository was assigned to the company effectively prevented any meaningful notifications about issues. We will finalise transferring the ownership of this repository in the next days, and integrate it into our open-source portfolio. We will also check the code for any further issues.
